version: '3.2'
networks:
  app-tier:
    driver: bridge
services:
  postgres:
    container_name: shop_postgress
    image: postgres
    volumes:
      - './.data/postgres:/var/lib/postgresql'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POOL: 100
    ports:
      - '5433:5432'
    networks:
      - app-tier
  shop:
    container_name: shop
    build: .
    volumes:
      - .:/app
    ports:
      - '4000:4000'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DATABASE: 'shop'
      POSTGRES_HOST: 'postgres'
    networks:
      - app-tier
 
volumes:
  pgdata:
  app:
